# render.yaml at repo root
services:
  - type: web
    name: floricode-backend
    env: python
    region: oregon
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    plan: free
    repo: https://github.com/Charaf-Floricode/Floricode-Dashboard
    branch: main
    workingDirectory: backend
    envVars:
      - key: FLORICODE_CLIENT_ID
        sync: false
      # …other backend secrets

staticSites:
  - name: floricode-frontend
    branch: main
    buildCommand: npm ci && npm run build
    publishDirectory: frontend/build
    rootDirectory: frontend
    plan: free
    repo: https://github.com/Charaf-Floricode/Floricode-Dashboard
    envVars:
      - key: REACT_APP_API_BASE
        value: https://floricode-backend.onrender.com/v1/
